### ISSUE TITLE
Network tab, hover over initiator distorting

### ISSUE THREAD

**Issue by nitinsurana** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#110]
The complete trace is not shown and kinda distorts the UI.

http://imgur.com/vAEBgEQ

**Comment by mauricecruz** [comment]
I think this is fixed now.  Please verify when you get a chance.

**Comment by mauricecruz** [comment]
is this still an issue?

**Comment by nitinsurana** [comment]
It's fixed.
