### ISSUE TITLE
When hovering over some properties the pop up displays a bubble with a scroll bar hiding the content

### ISSUE THREAD

**Issue by cyril-macisaac** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#116]
![image](https://cloud.githubusercontent.com/assets/8581220/6156497/c1984646-b208-11e4-90e2-818ea63691bc.png)

Sometimes when I hover over a property to get a preview it shows up with the preview bubble, but the bubble contains a scroll bar that hides the content. This happens fairly often with small string values it seems. Works fine without the Zero Dark theme applied.

**Comment by mauricecruz** [comment]
ahh.. thanks for reporting the issue. I fixed an issue with the text passing the bounds of the popup and I guess this is an inadvertent consequence. I'll look into it.

**Comment by mauricecruz** [comment]
I think I got this patched in v.1.6.8 which should be on the webstore shortly. Please verify when you get a chance.

**Comment by briantully** [comment]
https://github.com/mauricecruz/chrome-devtools-zerodarkmatrix-theme/issues/108

**Comment by mauricecruz** [comment]
hopefully this is fixed in 1.7.3

**Comment by mauricecruz** [comment]
ok.. still not fixed =|
![image](https://cloud.githubusercontent.com/assets/1640686/6854717/547e8808-d3c9-11e4-81ef-f4393163c88f.png)

**Comment by mauricecruz** [comment]
Fixed in v. 1.7.5
![image](https://cloud.githubusercontent.com/assets/1640686/6991357/d6373760-da5d-11e4-8b86-1e0cb0fdb1ab.png)
