### ISSUE TITLE
Network tab: last item is not visible when vertical scroll is present

### ISSUE THREAD

**Issue by malyw** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#118]
Environment: OS X Yosemite.
When plugin is turned off all is ok (not Chrome issue).
Screen: http://i.imgur.com/Ez19EiG.gif

**Comment by mauricecruz** [comment]
Thank for the report.  What version of Chrome?

**Comment by malyw** [comment]
Version 42.0.2309.2 canary (64-bit)
(I always update to the last version of Canary).
Started to appear about 3 weeks ago.

**Comment by mauricecruz** [comment]
Should be fixed in 1.7.0 which should be available shortly. Please confirm when you get a chance.

**Comment by malyw** [comment]
Now it's fixed. Thanks @mauricecruz
