### ISSUE TITLE
Booleans and integer colours in the console

### ISSUE THREAD

**Issue by MechJosh0** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#119]
Booleans and integers are dark blue on a black bacground in the console which is very difficult to read. http://i.imgur.com/ChPWxI0.png

**Comment by z1ck** [comment]
I confirm the problem.

**Comment by mauricecruz** [comment]
If you're talking about Canary, it should be fixed in v. 1.7.2

**Comment by mauricecruz** [comment]
![image](https://cloud.githubusercontent.com/assets/1640686/6841561/b4694954-d362-11e4-9f92-eac3932361d2.png)

**Comment by mauricecruz** [comment]
![image](https://cloud.githubusercontent.com/assets/1640686/6841582/ee7ead50-d362-11e4-8d13-fdd735285024.png)

**Comment by MechJosh0** [comment]
Fix confirmed. Thank you.
