### ISSUE TITLE
Hovering over variable shows scroll overlapping the variable value

### ISSUE THREAD

**Issue by nitinsurana** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#121]
Fiddle to replicate the issue. - http://jsfiddle.net/umb2mzoL/3/

![untitled](https://cloud.githubusercontent.com/assets/7137160/6936531/e0ad0b3c-d870-11e4-837c-aa51fbe07bdf.png)

**Comment by mauricecruz** [comment]
I think it's fixed now! I set a min height.

![image](https://cloud.githubusercontent.com/assets/1640686/6991355/b87ac836-da5d-11e4-99f8-ba635a142158.png)

**Comment by nitinsurana** [comment]
Works fine in 1.7.5
