### ISSUE TITLE
It is possible this theme throws out block indent/outdent using Tab/Shift+Tab

### ISSUE THREAD

**Issue by p-i-** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#122]
I just filed https://code.google.com/p/chromium/issues/detail?id=476379

However, as detailed in that issue follow-up,  The erroneous behaviour disappears if I use an Incognito window.

Therefore I suspect it may well be this theme throwing it out.

If that is the case, I pray for a fix, as I like this theme very much I will find it very difficult to go back to black-on-white.

Please do have a look to see if you can reproduce the problem.

π

**Comment by mauricecruz** [comment]
[resolved](https://github.com/mauricecruz/chrome-devtools-zerodarkmatrix-theme/issues/123#issuecomment-92299289)
