### ISSUE TITLE
(OSX) Can't right-click items in file treeview explorer panel

### ISSUE THREAD

**Issue by p-i-** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#123]
I was attempting to follow https://developer.chrome.com/devtools/docs/workspaces#mapping-a but failed at first instruction:

  1. In the Sources panel, right-click or Control+click on a file on the website.

In fact right-click doesn't work on *any* item In the file-view.   I had to disable the extension in order to complete the task.

**Comment by paulirish** [comment]
quite interested in this!

**Comment by mauricecruz** [comment]
What version of Chrome are you using? I wasn't able to reproduce using Chrome Stable on  OSX Yosemite.

FYI.. this was done on browserstack and I used right-click on the mouse.

![chrome-sources](https://cloud.githubusercontent.com/assets/1640686/7109695/d71515de-e170-11e4-9e08-77319aa2dc74.gif)

**Comment by p-i-** [comment]
Dayum.
I've just re-enabled `settings -> experiments -> allow custom UI themes` and it is working.
What's more, Tab & Shift+Tab now behave correctly for indenting and outdenting,  which is the other issue I flagged yesterday.

It is as if disabling and re-enabling have shaken something loose.

**Comment by mauricecruz** [comment]
@p-i- awesome! Someone else had a similar issue where [re-installing resolved their issue](https://github.com/mauricecruz/chrome-devtools-zerodarkmatrix-theme/issues/120#issuecomment-86530231). They don't seem related but maybe @paulirish can glean a pattern from it.
