### ISSUE TITLE
Error infobubble obscured by scrollbar

### ISSUE THREAD

**Issue by bbsimonbb** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#125]
Hi, since a

**Comment by bbsimonbb** [comment]
Hi, since a recent update (?), when I hover over the red cross on a failing line of javascript, the info bubble error message is obscured by a javascript. I love dark themes. Can this please be dealt with. I'm on Chrome 41.
![darkthemebug](https://cloud.githubusercontent.com/assets/11962703/7160277/4c11dbb0-e388-11e4-9418-9f57dac61cb8.png)

**Comment by mauricecruz** [comment]
thanks for the report. I'm able to reproduce it. I'll look into it.

**Comment by bbsimonbb** [comment]
A pleasure. Good luck.

2015-04-15 19:42 GMT+02:00 Maurice Cruz <notifications@github.com>:

**Comment by mauricecruz** [comment]
fixed in v 1.7.7 
![image](https://cloud.githubusercontent.com/assets/1640686/7211208/bce2d9e4-e526-11e4-80eb-9fa6c040e84c.png)
