### ISSUE TITLE
Some text hidden by white boxes

### ISSUE THREAD

**Issue by eldonzo** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#128]
I currently see 2 issues with Chrome 44.0.2377.0 canary (64-bit):

Part of the bottom bar of the files panel is covered with a white box, and when I'm in debug, part of the text on the line where I set the breakpoint is unreadable beacuse of the light background color.

![dark](https://cloud.githubusercontent.com/assets/4640236/7274836/85dc7da0-e900-11e4-99a1-99480a6ddc28.png)

I tried to inspect the elements, but I cannot find where is the issue.

**Comment by mauricecruz** [comment]
thanks for the report. Will look into it.

**Comment by mauricecruz** [comment]
@eldonzo fixed in 1.7.8. Please confirm.

**Comment by eldonzo** [comment]
@mauricecruz yes, everything is right now, thanks!
