### ISSUE TITLE
Image Hover Issue

### ISSUE THREAD

**Issue by cdymond** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#129]
Not sure how to descrive other than when you hover over a link for an image, instead of showing a small preview with the dimensions of the image, it's showing what I believe might be compressed scroll bars.

![devtoolsweirdness](https://cloud.githubusercontent.com/assets/3812608/7283453/afbb1132-e904-11e4-9d2d-c6eb119f92a7.png)

Version 43.0.2357.37 beta-m (64-bit)

**Comment by mauricecruz** [comment]
@cdymond is this still an issue? please confirm.

**Comment by wstow** [comment]
Yes, I see this for any variable when I put my cursor on it in the console.

Version 43.0.2357.81 m

**Comment by mauricecruz** [comment]
@wstow should be fixed in v1.8.0. If you have that version, please remove/add the extension again and let me know if that does it.

![image](https://cloud.githubusercontent.com/assets/1640686/7837640/4c7967e6-0456-11e5-88be-921f3a645813.png)

**Comment by wstow** [comment]
Removing/adding v1.8 fixed it.  Thanks!
