### ISSUE TITLE
Matching Sublime theme to this?

### ISSUE THREAD

**Issue by akanimh** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#130]
I was wondering which theme I should use in Sublime to match this? Any suggestions?

**Comment by mauricecruz** [comment]
Here's what I use. It's not exactly the same as the Chrome Devtools theme. Kinda never finished the CSS color highlighting of it. 

https://gist.github.com/mauricecruz/9e0501a34ec1382fb509

**Comment by akanimh** [comment]
Perfect! Thank you for sharing it.
