### ISSUE TITLE
Colors changed again

### ISSUE THREAD

**Issue by LeonardoGentile** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#133]
Hello again,
I don't know why but I guess that during development of chrome they keep on changing selectors, not sure why. Of course some little things of the extension won't work. Here some of them I found on Mac `45.0.2424.0 canary (64-bit)`  

- On `source` panel, under scope, nothing is visible unless we select them with the mouse
![image](https://cloud.githubusercontent.com/assets/412061/8031748/2746e83e-0dd1-11e5-8be2-b9cfb5069776.png)
![image](https://cloud.githubusercontent.com/assets/412061/8031756/3007c448-0dd1-11e5-9470-bd09268166bd.png)
- Same things as above under `Elements - Properties`
![image](https://cloud.githubusercontent.com/assets/412061/8031809/925bdf9e-0dd1-11e5-8af6-0e83ab5aabf2.png)
![image](https://cloud.githubusercontent.com/assets/412061/8031812/9ac9201a-0dd1-11e5-9886-965b4f4bbb83.png)
- Minor color issues
  - In Network panel
![image](https://cloud.githubusercontent.com/assets/412061/8031848/ed2a90fa-0dd1-11e5-9806-90bcc716bdc2.png)
  - In `Elements - styles`  
![image](https://cloud.githubusercontent.com/assets/412061/8031874/1efbc70c-0dd2-11e5-831c-9ee7ee20a070.png)

Thanks once again for your time and this useful tool :+1:

**Comment by mauricecruz** [comment]
Thanks for the report. Yup, pulled an update on Canary today and they did some markup/selector changes. 

Will patch when I get a free moment. Thanks.

**Comment by mauricecruz** [comment]
fixed in 1.8.3.
