### ISSUE TITLE
Doesn't load in Chrome Version 44.0.2403.89

### ISSUE THREAD

**Issue by dsine-de** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#135]
Chrome stable just updated on my PC and now the extension isn't loading anymore.

**Comment by mauricecruz** [comment]
Looks like the update reset the checkbox settings on the experiments tab. Can you check if allow custom ui themes is enabled?

**Comment by dsine-de** [comment]
Great, that's it. Totally forgot about that checkbox.

Thanks!
