### ISSUE TITLE
Doesn't seem to work on latest stable version, 44.0.2403.89

### ISSUE THREAD

**Issue by bpmarinho** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#136]
There was an update this week to chrome and this extension stopped working. Not sure if the problem is with Chrome or the extension.

Current version: 44.0.2403.89

**Comment by benlambt** [comment]
Still works, you just have to reenable it:

Open developer tools settings ▶ Experiments ▶ [✔] Allow custom UI themes.

**Comment by chrisg123** [comment]
I had the same issue. @benlambt is correct. it was just disabled. Just reenable and all is good.

**Comment by bpmarinho** [comment]
Just confirmed the solution. I checked the chrome://flags but forgot that extra step. Thank you.
