### ISSUE TITLE
Not working on latest Chrome version 44

### ISSUE THREAD

**Issue by altern8tif** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#139]
Working previously on Chrome until the latest Version 44.0.2403.155 (64-bit) on Mac OS X Yosemite 10.10.5.  Theme now reverts back to the default light theme.

Tried on incognito mode to eliminate possible conflicts with other plugins, but issue still persists.  DevTools Experiments Flag already enabled.

**Comment by cypherpunk** [comment]
It's not the flag, it's the setting in Devtools:
https://github.com/mauricecruz/chrome-devtools-zerodarkmatrix-theme/issues/135

**Comment by altern8tif** [comment]
@cypherpunk Aha... Thanks for that.  Will close the issue then.
