### ISSUE TITLE
Double click styling issue

### ISSUE THREAD

**Issue by s-KaiNet** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#140]
When double click on style or under elements tab words become black on black background. See attachments. Chome Version 46.0.2490.4 dev-m (64-bit)
![2015-08-27_1040](https://cloud.githubusercontent.com/assets/10658276/9515157/35c5222a-4ca8-11e5-8aa9-f78aaf8d76ff.png)
![2015-08-27_1039](https://cloud.githubusercontent.com/assets/10658276/9515158/35c6b3a6-4ca8-11e5-98ae-b4dd615f2a55.png)

**Comment by mauricecruz** [comment]
I've been trying to override it but I haven't found a solution to override shadow dom selectors that use the `!important` rule. I opened an issue with the chromium team, but they marked it as a wontfix.

Maybe starring it will make them reconsider? https://code.google.com/p/chromium/issues/detail?id=524599

**Comment by mauricecruz** [comment]
Put a band-aid in to make the background white. Not ideal, but it makes it functional for now. 
![image](https://cloud.githubusercontent.com/assets/1640686/9524115/2d4871d0-4cab-11e5-8a2a-47bddd955be0.png)

**Comment by mauricecruz** [comment]
resolved
