### ISSUE TITLE
Latest Chrome update screwed with things again

### ISSUE THREAD

**Issue by cypherpunk** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#141]
Clicking on properties to edit them becomes very light on white. They should be dark gray like selectors.

**Comment by mauricecruz** [comment]
What version are you running? I had to band-aid canary because they modified their css rules and I'm having difficulty overwriting them.

If this is related to your issue, please star this item.

**Comment by narcolepticinsomniac** [comment]
Same person, just signed up. 45.0.2454.85 m. I was reading that issue. Have you tried "-webkit-text-fill-color:" ? It overrides "color:!important;" without the "!important;".

**Comment by mauricecruz** [comment]
@narcolepticinsomniac awesome! that works. 

I'll patch it with that rule instead of reverting the background. I'll still try to get the devtools team to remove the specificity on their selectors since it's affecting other things.

Thanks for the tip!

**Comment by narcolepticinsomniac** [comment]
Not its intended use, but a handy little hack nonetheless. Glad I could help. I'm a big fan of this theme, keep up the good work.

**Comment by mauricecruz** [comment]
This is resolved.
