### ISSUE TITLE
chromium 43, missing arrows

### ISSUE THREAD

**Issue by mcelotti** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#142]
Hi, on my Chromium Version 43.0.2357.130 Ubuntu 14.04 (64-bit) I'm not able to see the arrows to open/close items/nodes/resources ecc.
If I click it toggles but it looks like the images are not visible:
![screenshot - 16092015 - 11 46 53](https://cloud.githubusercontent.com/assets/3830092/9901654/36d7649a-5c69-11e5-801f-a963bf07943a.png)

**Comment by mauricecruz** [comment]
Is that the latest version? Sorry, I don't keep track of the Chromium release cycles. Chrome Stable is available for Linux and they're at v.45. 

Would that work for your machine?

**Comment by mcelotti** [comment]
Hey Maurice, I've upgraded to latest chromium (44) and now it works, sorry to bother you.

Thanks,
Marco

**Comment by mauricecruz** [comment]
:+1: no worries!
