### ISSUE TITLE
Animations Controls panel needs some love

### ISSUE THREAD

**Issue by Iwasawafag** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#144]
Here's two screenshots for comparison

![](http://i.imgur.com/5MgHNn4.png)
![](http://i.imgur.com/iLoTZUR.png)

It's an experient though (called "Animation Inspection"), not a finished feature so it may change, but I would like to have it readable with this dark theme. 
Google Chrome ver: 45.0.2454.101 m (64-bit)

And in case if you're not gonna bother with experimental features, can we possible have an options page then with a custom styles field, so we can style things we need by ourselves?

**Comment by mauricecruz** [comment]
I'll get to it this week. Thanks for reporting!

**Comment by mauricecruz** [comment]
Haven't gotten round to styling the animations panel yet but I do intend to style some experimental features.

Alternatively you can clone this repo and style anything to your liking - https://github.com/mauricecruz/zero-base-themes

**Comment by mauricecruz** [comment]
In latest build on webstore.

![image](https://cloud.githubusercontent.com/assets/1640686/10750367/edac0f3a-7c4a-11e5-828c-fe3d6ce5a036.png)
