### ISSUE TITLE
Linux Chrome v45 styling issues

### ISSUE THREAD

**Issue by jsalankey** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#145]
I've noticed two styling issues in Chrome v45 that only occur in Linux (seem to be fine here in Windows). Unfortunately I can't handily get screenshots, but I will do my best to describe them:

* The filters dropdown on the network tab and the console have an incorrectly colored background when active. It's still a bright white-ish gray.
* When paused at a JS breakpoint in, the hover styles on the rows in the call stack seem to be off. Odd rows are getting colored with the same bright white and even rows don't get a hover style at all.

**Comment by mauricecruz** [comment]
Any luck with screenshots?

**Comment by mauricecruz** [comment]
Stable is at v46 now. If you still have issues, please reopen.
