### ISSUE TITLE
Canary 46 issues

### ISSUE THREAD

**Issue by LeonardoGentile** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#146]
Hello,
these issues are happening in Chrome 46.0.2490.71 (64-bit)
- Source Panel -> cmd-p -> up/down arrows not working for selecting the script to debug
- Color inconsistencies (I'll try to be more specific as they occur) spread a little bit around. Specifically something that should be black or have a black background is usually white/white bg.

**Comment by mauricecruz** [comment]
Pushed a sorta fix for canary. Just a few more updates to fix some layouts in the settings pane. Let me know the latest update addresses your issues though.

**Comment by LeonardoGentile** [comment]
Thanks @mauricecruz, are you fixes only here on github or also in chrome web store?

**Comment by mauricecruz** [comment]
Should be on the store.



- Maurice

**Comment by mauricecruz** [comment]
canary's at v48 now so please open another issue if there's unstyled parts. FYI.. there's unstyled parts in v.48 I haven't gotten to yet =).

**Comment by LeonardoGentile** [comment]
@mauricecruz sorry I haven't replied you sooner. Your fixes seems to work (cmd-p, then arrow, then selection). Thanks a lot! :+1: 

Where are the majority of the unstyled parts in 48? So I will avoid opening another issue if you have already figure them out :)

**Comment by mauricecruz** [comment]
no prob! Most of the unstyled parts are in the settings menu.
