### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by xiaojiangjiang** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#147]
It is a awesome tool! I like it so much.But the navy blue is so hard to see clearly on a black background.If you can change the navy blue to white or some lighted color, it will be great!

**Comment by mauricecruz** [comment]
can you paste a screenshot of what you mean?

**Comment by xiaojiangjiang** [comment]
![image](https://cloud.githubusercontent.com/assets/8230871/10598023/63e5f52c-7727-11e5-9ef9-3ea46cefb35d.png)
like this

**Comment by mauricecruz** [comment]
Can you tell me what version you're using? This is a screenshot from v46 stable 

![image](https://cloud.githubusercontent.com/assets/1640686/10649422/0d33f742-7812-11e5-9fae-225c56cc82d1.png)

**Comment by xiaojiangjiang** [comment]
![image](https://cloud.githubusercontent.com/assets/8230871/10654597/f62de462-789e-11e5-8507-add0a381a291.png)
platform: iMac

**Comment by mauricecruz** [comment]
Can you update? Stable is 5 versions ahead.

**Comment by xiaojiangjiang** [comment]
Ok thanks for answering ^_^

**Comment by mauricecruz** [comment]
no prob!
