### ISSUE TITLE
Mac Scrollbar Styling

### ISSUE THREAD

**Issue by wsoyka** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#148]
On Mac (10.10.3), Chrome (46.0.2490.71) sometimes some of the scrollbars are not styled correctly, or rather not styled at all. Cycling through the tabs of the DevTool (Elements, Network, Sources, etc) seems to fix the problem.

I got all possible combinations on the Elements tab, namely the right scrollbar, the left scrollbar and both scrollbars not being styled. See the screenshot below.
![Both not styled](https://cloud.githubusercontent.com/assets/2890574/10701463/e5f4e93a-79c3-11e5-9f95-40bc6cd2f70d.png)

Also note the ugly right lower corner which is for some reason always white. (Not related to the scrollbar issue)
Both those things are visually really annoying. Could you fix any of this?

Nice style and best regards,
Wolfram

**Comment by mauricecruz** [comment]
Also get them on windows. It happens everytime I open devtools. What I think is happening is that the scrollbar ui loads before the theme css loads. And when the css is parsed, it doesn't trigger a repaint on the scrollbar so the native style stays. But once you change tabs or force a repaint, it takes the scrollbar css into consideration.

I made all that up but it makes sense to me =D. 

In any case, within the scope of css, I don't know how I can fix it. I'm open to ideas.

**Comment by wsoyka** [comment]
Sounds reasonable, afterall this has not yet happened to me when the scrollbar was added post devtool opening time (read: open all the divs). Idk how or where this style is applied, but could you maybe do something like [this](https://stackoverflow.com/questions/3485365/how-can-i-force-webkit-to-redraw-repaint-to-propagate-style-changes)?

**Comment by mauricecruz** [comment]
The style is applied via a devtool api that simply allows me to inject css into the sandboxed devtools environment. I won't be able to use any javascript to trigger a paint.
