### ISSUE TITLE
Almost invisible caption in the screenshot view

### ISSUE THREAD

**Issue by fatfisz** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#149]
As in the attached image, the number of ms is almost invisible (black on the dark grey background).
It's in the Network panel.
Chrome version: 46.0.2490.80 m.

![screen2](https://cloud.githubusercontent.com/assets/6004414/10814099/c5727dbc-7e23-11e5-87bd-907830c14dc4.png)

**Comment by mauricecruz** [comment]
thanks will fix soon

**Comment by mauricecruz** [comment]
fixed in v.2.0.2. Should be in webstore shortly.

**Comment by fatfisz** [comment]
It works, thanks :)
