### ISSUE TITLE
XML blends in with preview tab in network

### ISSUE THREAD

**Issue by dhershman1** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#150]
This is the same comment I posted on the actual extension page, sorry I didn't notice your reply until today.

The background of the theme makes it harder to read xml code replies in preview as shown below

![Example Image](http://i.imgur.com/uEtDpiO.png)

**Comment by mauricecruz** [comment]
Thanks for the screenshot. Do you know what type of extension or type of file triggers this preview? Or maybe a url?

**Comment by dhershman1** [comment]
The most I know behind it is the site makes an ajax call to a resource which returns a response in xml. Most of the XML is setup in a .handlebars file however.

**Comment by tribou** [comment]
This may be related to certain views used by many chrome extensions...

Here's the attributes section of Ember Inspector:

![screenshot](https://cloud.githubusercontent.com/assets/1641390/12888176/58b9d9ca-ce3e-11e5-8d12-5a5eca80ba8c.png)

**Comment by mauricecruz** [comment]
Thanks for the report. Last I remember, there wasn't any selector hook that
I could use to disable the background on plugins. I'll check again. Things
may have changed.



- Maurice

**Comment by mauricecruz** [comment]
Is this still an issue? Please let me know.

**Comment by dhershman1** [comment]
Doesn't look like it, went back to check and seems like the XML is syntax colored correctly.
