### ISSUE TITLE
Triangle Arrows not turning down in Elements and Objects in Console

### ISSUE THREAD

**Issue by jasonhuang0324** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#153]
Hi Maurice, I have recently reinstalled my chrome and reinstalled this awesome extension, but just found out recently that the triangle arrows in html elements view and objects in console has an issue, that is the triangle arrows wouldn't point down after going down into the tree (can't recall whether it's there already before reinstalling chrome), it's sometimes quite confusing even with the indentation. A screenshot is provided below, and my chrome version is **Version 49.0.2587.3 (64-bit)**
![image](https://cloud.githubusercontent.com/assets/2591880/11838713/c5e27f42-a423-11e5-97cd-eb7ec608b5df.png)

**Comment by mauricecruz** [comment]
Thanks for the report. This is Canary channel right? I noticed it a week or so ago hoping it would be resolved in the next iteration. 

Seems like animations no longer are working for these dom nodes. I'll disable it the animation for now.

**Comment by jasonhuang0324** [comment]
I'm on the Dev channel, and it seems to be working originally for chrome, see the incognito view screenshot below.
![image](https://cloud.githubusercontent.com/assets/2591880/11862115/0d715060-a4c2-11e5-8422-20a333a31ec9.png)

**Comment by mauricecruz** [comment]
Thanks Jason. I remove the arrow animations for now. Has something to do with the internals of chrome. 

It's only broken on v.49 on the elements panel. Everything else is fine.

Update should be in the store shortly.
