### ISSUE TITLE
When changing elements css styles doesn't change

### ISSUE THREAD

**Issue by Jules2010** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#155]
Hi,

In the last update of chrome the plugin seems to fail to allow selection of new elements.

So I would select a different html element and the style would not reflect the selection.

Disabling the extension fixes the issues.

Really love this extension, so would be pleased to see a fix.

Would be happy to test it too.

Jules.

**Comment by Jules2010** [comment]
Hi

Yes the element panel. I click on a html element and the contents of the styles box doesn't change.

I select another element an still nothing changes in the style box.

I have to restart my browser.

Then I can select styles for a short time.

The expected behaviour would be to select a html element and see the css style for it in the style box. Then when selecting another element have the styles box reflect the different style.

**Comment by mauricecruz** [comment]
I see. Hmm that sounds a bit difficult to troubleshoot since it sounds like some piece of logic is not executing to update the UI. But my theme only affects css. Will definitely look into it and try to reproduce. Can you provide your OS and browser version please.

**Comment by Jules2010** [comment]
Windows 10 and chrome 47.0.2526.106m (64 bit)

**Comment by Jules2010** [comment]
This issue happens in chrome, so it's probably nothing to to the zerodark.
