### ISSUE TITLE
ZeroDarkMatrix theme is hiding the mobile emulator icon, devtools settings bullet icon & [X] closing icon

### ISSUE THREAD

**Issue by davelaflam** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#157]
When applying the ZeroDarkMatrix theme it is hiding the mobile emulator icon on the left side of the devtools task bar as well as hiding the devtools setting vertical three dot icon & [X] closing icon on the far right of the devtools task bar.

I'm not exactly sure when this started happening but I think it was very recent as I remember seeing and using the icons fairly recent.

Attaching a screen shot without the ZeroDarkMatrix theme showing the icons and then when the theme is applied those icons are hidden.
![toolbar-mobile-settings-icons-hiding](https://cloud.githubusercontent.com/assets/362749/12932522/1c8b731e-cf38-11e5-9b57-ef7edddb7a81.jpg)

**Comment by mauricecruz** [comment]
Thanks for the report. I'll fix asap. Please let me know what version
you're on.



- Maurice

**Comment by davelaflam** [comment]
Chrome Version 48.0.2564.109 (64-bit)

**Comment by mauricecruz** [comment]
@davelaflam is this still an issue? I'm having trouble replicating on stable.

**Comment by davelaflam** [comment]
Weird, about a week ago those icons became visible again so I thought you may have put in a fix but it looks like it corrected itself and those icons are now visible. On a side note, I came across this post http://bit.ly/1mTfPrr that they are now going to bake in a dark them for dev tools. It's currently in canary and looks like it'll be released in the stable v49. Thanks again for all your help.
