### ISSUE TITLE
Scroll gets stuck in Network panel

### ISSUE THREAD

**Issue by g-akshay** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#158]
When one scrolls to the end of network panel, the scroll becomes unresponsive.

**Comment by mauricecruz** [comment]
@g-akshay sorry for the non-response. Totally missed this. Is this still an issue?

**Comment by g-akshay** [comment]
yes its still there. I have started using chrome's inbuilt black theme, though will love to move back to zero dark matrix.

**Comment by mauricecruz** [comment]
@g-akshay not sure if you're still using the theme. If so, please let me know if your issue still persists.

**Comment by g-akshay** [comment]
I am not using any theme as of now as few versions back chrome shipped with its own black theme. 
Closing the issue.
