### ISSUE TITLE
Doesn't show pretty in Chrome Version more than 49

### ISSUE THREAD

**Issue by yangzj1992** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#160]
My Chrome version is 49.0.2623.75 (64-bit). In this new version, Chrome has changed the style of their mobile device debug mode.So the theme view has become like [this](http://qcyoung.qiniudn.com/qcyoung/theme-in-chrome-49.png). Can we unify the mobile device display area and developer panel area in consistent style?

**Comment by johny-gog** [comment]
I would rename this to:

Not compatible (ugly) with mobile device mode in newest Chrome (>=49)

I would love this to be resolved! :+1:

**Comment by mauricecruz** [comment]
Thanks for the report. Will address within the week.



- Maurice

**Comment by mauricecruz** [comment]
fixed in v. 2.1.1 on webstore
