### ISSUE TITLE
Broken in Chrome v 49.0.2623.87 

### ISSUE THREAD

**Issue by mladenp** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#161]
I have been using this theme for a long time and i think this is the first time its been broken.
I am using Chrome v 49.0.2623.87 on Windows 10.

**Comment by mauricecruz** [comment]
Thanks for the report. Can you give me some details what type of broken it is?

**Comment by mladenp** [comment]
Here is screenshot: [http://imgur.com/Y4w3IcA](url)

**Comment by mauricecruz** [comment]
Hmm.. using the same version on Mac and all looks well. Can you try uninstalling the plugin and reinstalling?

**Comment by mladenp** [comment]
I did that already, i also don't have any other extensions for DevTools.

**Comment by mauricecruz** [comment]
ok.. will test on win 10. Thanks!

**Comment by mauricecruz** [comment]
Can't seem to reproduce on Chrome 49 on win10 via Browserstack.

![image](https://cloud.githubusercontent.com/assets/1640686/14020735/da38e728-f1ae-11e5-8c2b-d5ca7f7271f3.png)


By any chance, are you using remote devtools and rendering a devtools session to debug an android chrome browser?

**Comment by mauricecruz** [comment]
@mladenp just checking if you were able to resolve or can provide additional info.

**Comment by mladenp** [comment]
Nope, tried cleaning up my Chrome a little but nothing helped. 
I guess there are more users with Windows 10 and latest Chrome version but i didn't see anyone here mentioning this problem. 
I'll try to clean install Chrome and see if that fixes the problem.

**Comment by mauricecruz** [comment]
@mladenp still experiencing issues? Stable should be on v50 now.

**Comment by mladenp** [comment]
I installed it again on v50 and it works fine.
