### ISSUE TITLE
Loose permissions

### ISSUE THREAD

**Issue by tonybaroneee** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#162]
Hey, love the extension! Would you be able to specify the exact permission(s) you need in your manifest file? It's currently asking for read/write access to all data when installing, which seems unnecessary for what this extension is actually doing (just loading an extra stylesheet).

Thanks!

Reference: https://developer.chrome.com/extensions/permissions

![https://s3.amazonaws.com/uploads.hipchat.com/153887/1539576/5ynulVl8XFMQFP2/upload.png](https://s3.amazonaws.com/uploads.hipchat.com/153887/1539576/5ynulVl8XFMQFP2/upload.png)

**Comment by mauricecruz** [comment]
Sure thing! Thanks for the info.



- Maurice

**Comment by mauricecruz** [comment]
Looked into the possible permission settings and it looks like that warning is put up if a 'devtools' page is used. 

Doesn't look like I'll be able to remove it with the current way themes are injected into devtools. Thanks for bringing this to my attention though!

**Comment by tonybaroneee** [comment]
Sounds good, thanks for digging in!
