### ISSUE TITLE
Style controls are off-screen in Canary 52.0.2709.0

### ISSUE THREAD

**Issue by JayGeorge** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#163]
This has been broken for maybe a week or two.

The Style controls you normally see in the Elements tab are overflowing to the right.

I’ve attached a gif showing them working as fine when I launch normal devtools (without custom UI themes), and then them overflowing using Zero Dark Matrix.

![normal devtools fine](https://cloud.githubusercontent.com/assets/693601/14556984/d9ffbec6-02f2-11e6-876f-8715ecae8f29.gif)
![zero based](https://cloud.githubusercontent.com/assets/693601/14556985/d9ffd67c-02f2-11e6-9531-f6ab47c83add.gif)

**Comment by mauricecruz** [comment]
@JayGeorge what is the 2nd icon from the right next to the +? I'm missing that from my devtools

**Comment by JayGeorge** [comment]
Oh that’s the Layout Editor; an experiment in Devtools.

Without that turned on the results are still the same though. This is Canary btw.

**Comment by mauricecruz** [comment]
Is that behind a flag? How do I get that turned on?

**Comment by JayGeorge** [comment]
In the settings under experiments tap shift 6 times to get extra stuff.
It’s there.
![screenshot 2016-04-15 15 32 04](https://cloud.githubusercontent.com/assets/693601/14564612/490c079e-031f-11e6-9253-bfa9c85eb7e4.png)

**Comment by mauricecruz** [comment]
Ahh sweet. Haven't look in there in awhile. Thanks! I'll get to a fix soon!



- Maurice

**Comment by mauricecruz** [comment]
definitely having trouble reproducing on same canary version on mac. gonna try using a virtual and validating on a clean install.

**Comment by mauricecruz** [comment]
@JayGeorge wasn't able to reproduce on virtual. Are you loading via chrome webstore or custom built package?

**Comment by mauricecruz** [comment]
Can you try the webstore version and let me know if it's still an issue.

**Comment by JayGeorge** [comment]
Hey, I re-installed Canary and it’s fine now, even with the experiments
turned on.

You know what it might have been? I had previously ticked the experiment
"Reduced indentation in Elements DOM tree"
But I don’t want to try it again in case it messes stuff up!

**Comment by mauricecruz** [comment]
@JayGeorge thanks for the response. I turned that one on but couldn't replicate. Glad you got it working though!
