### ISSUE TITLE
Settings > Shortcuts screen keystrokes are dark-on-dark

### ISSUE THREAD

**Issue by quinncomendant** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#164]
In Chrome v50, the dev tools Settings > Shortcuts page displays they keystrokes as dark on a dark background, i.e., not readable. Screenshot:

![screen shot 2016-05-11 at 20 58 50](https://cloud.githubusercontent.com/assets/6884276/15201933/8ad4e73a-17bb-11e6-8bd8-50450e3f0f76.png)

**Comment by mauricecruz** [comment]
Ahh, I think you have the 'dark' native theme setting enabled. The theme was built to stack on the original 'default' theme. You can switch to the default theme so the keys render properly.

I'll look into what it will take to support stacking over the dark theme.

**Comment by quinncomendant** [comment]
Yep, that's exactly what's happening. I wasn't aware Chrome had a built-in dark theme, and must have selected it in confusion. zerodarkmatrix is nicer though. =)

**Comment by mauricecruz** [comment]
Thanks! The native theme is... inspired by this theme, so they look very
similar.
