### ISSUE TITLE
New Dev-tools break Style in autocomplete

### ISSUE THREAD

**Issue by hutzlibu** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#165]
Since the dev-tools introduced a new autocomplete-feature (of all the input you made?)
it breaks style:
![chrome dark](https://cloud.githubusercontent.com/assets/7058891/15247098/1a648962-1912-11e6-95c4-a421294d11a3.jpg)

Oh, and I really like your work, btw. ...

**Comment by mauricecruz** [comment]
The styles are working in v. 50.0.2661 of Chrome and 2.1.4 of the theme. Can you verify you're on the latest version and let me know what OS you're using?
![](http://take.ms/izR1w)

**Comment by hutzlibu** [comment]
Ah ... the problem was the version. 
Because I did not installed through the web-store, rather than downloaded the zip from github 
And this version seems to be outdated ...
