### ISSUE TITLE
Can you modify color scheme at the React tab?

### ISSUE THREAD

**Issue by Enclave88** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#166]
Right now it's too difficult to read.

For example my screenshot:
[https://www.dropbox.com/home?preview=Screenshot+from+2016-07-05+15-33-03.png](url)

About system:
Ubuntu 16.04, Google Chrome Version 51.0.2704.106 (64-bit)

**Comment by mauricecruz** [comment]
screenshot is 404

**Comment by Enclave88** [comment]
@mauricecruz, sorry for that, [here it is!](https://s32.postimg.org/68yxdqglx/Screenshot_from_2016_07_05_15_33_03.png)

**Comment by mauricecruz** [comment]
I can't modify the text because styles are sandboxed. And also, they're using inline styles.

But - I was able to paint the background white for the react theme. Update should be in webstore shortly.

![image](https://cloud.githubusercontent.com/assets/1640686/16592307/13fb8592-42ae-11e6-963e-2b3e6f1cc24e.png)

**Comment by Enclave88** [comment]
Thanks! That's much better!

**Comment by Enclave88** [comment]
Hello @mauricecruz! Something css troubles again. On the **Errors**, **Info** and **Debug** tabs:

![screenshot from 2016-12-21 13-54-49](https://cloud.githubusercontent.com/assets/5970902/21381426/775f579c-c785-11e6-8b37-c82f9e86c69b.png)
![screenshot from 2016-12-21 13-54-55](https://cloud.githubusercontent.com/assets/5970902/21381427/7762d084-c785-11e6-8a68-9a9e88fbdb0a.png)
![screenshot from 2016-12-21 13-59-31](https://cloud.githubusercontent.com/assets/5970902/21381481/c38c1632-c785-11e6-8b23-2a405c26c771.png)

**Comment by mauricecruz** [comment]
pushed a fixed on v.2.2.3 - Please verify because I'm having trouble replicating the issue.
