### ISSUE TITLE
No options

### ISSUE THREAD

**Issue by Shiro-dono** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#167]
I did all the steps, but I can't get into the options to activate the custom UI.

**Comment by mauricecruz** [comment]
Make sure you click relaunch now after you check off the devtools experiments checkbox

![](http://take.ms/yyRsc)

**Comment by Shiro-dono** [comment]
Hello, yes i did that, and re did everything
But I still have this
L![untitled-1](https://cloud.githubusercontent.com/assets/13037716/17135406/5175ffa2-5338-11e6-8d4f-f62f70db1d59.jpg)

**Comment by mauricecruz** [comment]
@Shiro-dono that menu won't bet you to the settings to turn on the devtools theme. You'll have to open developer tools (ctrl/cmd + shift + i), open the settings menu , select the experiments tab and then check off 'allow custom UI themes'

![](http://take.ms/MJ9Xb)
![](http://take.ms/4Xyhs)

**Comment by mauricecruz** [comment]
Are you still experiencing issues?

**Comment by Shiro-dono** [comment]
Hello, thx for the concern, indeed it works, i have forgotten about the settings that chrome has (F1) from inspect element, I found the stuff and I chose the Dark (Side) Theme.

**Comment by mauricecruz** [comment]
Awesome. Thanks!
