### ISSUE TITLE
support Chrome 53 Application panel background color using theme's color

### ISSUE THREAD

**Issue by whq731** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#168]
This is a great theme.
Chrome 53 adds Application panel .
Hope theme can support it .
<img width="721" alt="2016-08-15 4 39 57" src="https://cloud.githubusercontent.com/assets/5442362/17659768/4dbcde06-6307-11e6-9a83-4621bbe90ddd.png">

**Comment by mauricecruz** [comment]
thanks for letting me know. Will take a look when I get a free moment.

**Comment by mauricecruz** [comment]
this is styled in v2.1.8. Should be available shortly.
