### ISSUE TITLE
syntax highlighting when working with Chrome console

### ISSUE THREAD

**Issue by m98** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#169]
Maybe someone before asked this, but this is what I think can be really great to add to the _chrome-devtools-zerodarkmatrix-theme_

For example, I want to write simple test inside my chrome console (developer tools), but it is just simple text and does not have any color, that would be great if you could add some simple colors to brackets, parentheses, and commas.

I know there are limitations too, but that was just an idea/suggestion.

_EDIT:_
I know the extension now colorize the syntaxes, but I mean colorizing it while typing the code, not after pressing the enter.

Thanks for your efforts :+1:

**Comment by mauricecruz** [comment]
Great suggestion. I can look into what's available. I'm limited to what CodeMirror recognizes.
