### ISSUE TITLE
It doesn't work in Version 53.0.2785.116 m (64-bit)

### ISSUE THREAD

**Issue by yinhaibo01** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#170]
As title, I like this extension very much.
But I can not use it after updating the chrome to the latest version.

**Comment by yinhaibo01** [comment]
Uh-oh;
I fount it, the latest chrome has the console theme: default and dark.
Thank you very much, maybe chrome team learned this from you

**Comment by mauricecruz** [comment]
Yes, the devtools added a native dark theme with similar colors. There are minor differences but for the most part, it does the job. Enjoy!
