### ISSUE TITLE
Line numbers in source view are light green

### ISSUE THREAD

**Issue by dsmeltz** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#171]
I think this started with the latest Chrome update.  The line numbers in the source view are light green.   If the background was just dark I think that would solve the issue.  (See screen shot)

![image](https://cloud.githubusercontent.com/assets/1830600/18849071/32c3f044-83ff-11e6-9429-dc8ff6dff47b.png)

**Comment by mauricecruz** [comment]
Thought I reverted it. I'll check it out.  Thanks!

**Comment by mauricecruz** [comment]
Ahh forgot to publish the revert. Should be available on the web store soon.

**Comment by mauricecruz** [comment]
Can you confirm if this is fixed for you?

**Comment by dsmeltz** [comment]
Looks great! Thanks
