### ISSUE TITLE
Color rendering faulty? Breaks usage for colorblind users

### ISSUE THREAD

**Issue by khaivngo** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#175]
See image for example: http://puu.sh/sWrmL/3df276eb2d.png
This is worrying because for colorblind people this is invisible!

**Comment by david-salvador** [comment]
I was going to add the same issue; for me it happens in objects in the console.

**Comment by mauricecruz** [comment]
@khaivngo - getting 404 on screenshot. Can you re-upload?

**Comment by khaivngo** [comment]
Github doesn't seem to link it properly, copy the link and paste it in the
address bar.

Khai

**Comment by mauricecruz** [comment]
I see. Thanks. Another user reported this issue but I'm having trouble replicating. Is there a specific setting toggled for colorblind users?

**Comment by khaivngo** [comment]
No extra options or plugins have been added to the console. Just the
minimum requirements for your dark theme.
Occurred today.

**Comment by mauricecruz** [comment]
Gotcha.  What version of chrome are you on?

**Comment by khaivngo** [comment]
Version 55.0.2883.87 m

**Comment by mauricecruz** [comment]
pushed a fixed on v.2.2.3 - Please verify because I'm having trouble replicating the issue.

**Comment by dashukin** [comment]
Hi @mauricecruz 
Seems to be still valid for
Chrome: 55.0.2883.87 m (64-bit) 
Theme: 2.2.4
![2016-12-22_0952](https://cloud.githubusercontent.com/assets/5929682/21417547/64059c04-c82c-11e6-8dd6-3d6ce2354564.png)

**Comment by khaivngo** [comment]
Everything seems to be working now, thanks for the quick fix.

**Comment by david-salvador** [comment]
Confirmed it works! Thanks for the responsiveness.
