### ISSUE TITLE
unreadable console output for objects

### ISSUE THREAD

**Issue by luckylooke** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#176]
Today console started to add some background color to objects outputs. I cannot get rid of it.
http://prntscr.com/dm542o

**Comment by mauricecruz** [comment]
Whoa - sorry about that. What version are you using and can you give me steps to replicate? Not seeing that on v55 stable

**Comment by phoxoey** [comment]
Yesterday was fine, today; I'm getting this:
![console_image](https://cloud.githubusercontent.com/assets/7294128/21391549/2f41362c-c75a-11e6-98cf-fb5d4c3c5de6.jpeg)

**Comment by mauricecruz** [comment]
Fix on the way

**Comment by phoxoey** [comment]
Awesome sauce.

**Comment by mauricecruz** [comment]
pushed a fixed on v.2.2.3 - Please verify because I'm having trouble replicating the issue.

**Comment by szuranski** [comment]
![image](https://cloud.githubusercontent.com/assets/4400466/21397699/6bde549c-c76a-11e6-8447-01ffefa8d0aa.png)
![image](https://cloud.githubusercontent.com/assets/4400466/21397738/85b4079a-c76a-11e6-8e5b-1be5b6d629ff.png)

v.2.2.3 fixes the issue for me.

**Comment by szuranski** [comment]
![image](https://cloud.githubusercontent.com/assets/4400466/21398040/9165933c-c76b-11e6-8541-b66cf300ff03.png)

Not an usability issue but the last version looks like it affected the side panel color.

**Comment by mauricecruz** [comment]
Ah - thanks. On it.

**Comment by mauricecruz** [comment]
@szuranski pushed a fix on 2.2.4.

**Comment by phoxoey** [comment]
2.2.3 / 2.2.4 push fixed it for me. Thanks!

**Comment by szuranski** [comment]
Fixed. Thanks!!!

**Comment by luckylooke** [comment]
Fixed for me too, @mauricecruz thank you for your patient maintenance ;)
