### ISSUE TITLE
Network -> preview is not readable

### ISSUE THREAD

**Issue by sohexcore** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#178]
Is there any way I can make that text white/gray?
![01](https://cloud.githubusercontent.com/assets/560402/22117780/87f5236e-de75-11e6-8235-cf17694cfbb3.png)
![02](https://cloud.githubusercontent.com/assets/560402/22117779/87f4815c-de75-11e6-9e40-56573d8d1e8b.png)

**Comment by mauricecruz** [comment]
Can you put this example up on a codepen or fiddle? I'll need to see if there's a selector I can hook on to for that type of response.

**Comment by returnlytom** [comment]
First of all, keep up the great work Maurice - this is by far the one extension I couldn't live without :)

Just wanted to add to this thread that I noticed it in the *Request Payload* tab as well:

![image](https://cloud.githubusercontent.com/assets/22224829/23774812/75377656-04da-11e7-80f7-c80d4ddaf8ea.png)

**Comment by mauricecruz** [comment]
@returnlytom Glad you enjoy it! 

I'll look into fixing those colors. Thanks for reporting.

**Comment by mauricecruz** [comment]
@returnlytom just pushed out a fix - can you verify?

**Comment by returnlytom** [comment]
![image](https://cloud.githubusercontent.com/assets/22224829/23962956/022b0c8a-096d-11e7-9602-14f5ce43e0db.png)

Looks great, thank you for the quick fix!
