### ISSUE TITLE
What error ?

### ISSUE THREAD

**Issue by lehoangnam14** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#179]
![ui theme error](https://cloud.githubusercontent.com/assets/7042462/22625049/13cdc972-ebbe-11e6-812f-787e634ca9c9.png)

Thanks !

**Comment by mauricecruz** [comment]
Just released a fix on the webstore (v2.2.6). Please let me know if it works!

**Comment by lehoangnam14** [comment]
I using version v2.2.6 :(
![image](https://cloud.githubusercontent.com/assets/7042462/22632366/1fa12b08-ec4b-11e6-9bd1-f146f880dc91.png)

**Comment by mauricecruz** [comment]
What version of chrome are you on?

**Comment by lehoangnam14** [comment]
This is version of chrome:
![image](https://cloud.githubusercontent.com/assets/7042462/22632907/c2c216c2-ec4f-11e6-9dde-0be05805be3f.png)
