### ISSUE TITLE
Error in chrome 57

### ISSUE THREAD

**Issue by hoangnamitc** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#182]
![image](https://cloud.githubusercontent.com/assets/7042462/23843371/f0ce7e52-07ed-11e7-9409-61fac2cbd718.png)

Please Update fix. Thanks author !

**Comment by dare023** [comment]
I can confirm issue. 
Arch Linux / Plasma 5
Thank you in advance for fix.

**Comment by mauricecruz** [comment]
What version of chrome?



- Maurice

**Comment by mauricecruz** [comment]
looking into it. Thanks!

**Comment by mauricecruz** [comment]
Fix should be in the webstore shortly.

**Comment by dare023** [comment]
Thank you for quick fix!
