### ISSUE TITLE
Info: DevTools now have a dark theme out of the box

### ISSUE THREAD

**Issue by mrchief** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#183]
This has been a "can't live without" extension for years. But finally, Chrome DevTools now support dark theme out of the box: [developers.google.com/web/updates/2016/02/devtools-digest-devtools-go-dark](https://developers.google.com/web/updates/2016/02/devtools-digest-devtools-go-dark#a_dark_theme_for_devtools)

![image](https://cloud.githubusercontent.com/assets/781818/24370966/4e45d58a-12f7-11e7-962a-888de221007f.png)

A benefit of being out of the box is that now 3rd party extensions that add a tab (like Cookie Inspector) now work without any tweaks. 

![image](https://cloud.githubusercontent.com/assets/781818/24371031/8a539d8c-12f7-11e7-9f96-ac4e1da6476f.png)

That said, hats off to @mauricecruz for putting this extension out there in times when Google left us in dark (or not in dark). 

And you still need this extension if you don't like the default dark colors put out by Chrome team.

**Comment by mauricecruz** [comment]
Thank you for the compliments! The native dark theme definitely helps keep styles consistent without this theme.

Though if you still enjoy the other features of this theme, it stacks well with the native dark theme. So feel free to continue using it. I plan to continue to support it until they close the doors on custom theming.
