### ISSUE TITLE
double quotation in console is black

### ISSUE THREAD

**Issue by wowdyaln** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#184]
can I adjust these by myself ?
<img width="477" alt="quote color is black_2" src="https://cloud.githubusercontent.com/assets/17491125/26104271/aa2c73d2-3a6f-11e7-9a40-54d0d13c7861.png">
<img width="473" alt="quote color is black" src="https://cloud.githubusercontent.com/assets/17491125/26104280/b4eb2a8e-3a6f-11e7-9171-ad22762b7f87.png">
thank you

**Comment by wowdyaln** [comment]
to solving this issue as follow :

<img width="326" alt="screenshot at 5 31 15-18-34" src="https://cloud.githubusercontent.com/assets/17491125/26620298/d812cb92-4614-11e7-8923-4e984b9d1edb.png">

switch theme to "dark"
<img width="217" alt="screenshot at 5 31 15-25-38" src="https://cloud.githubusercontent.com/assets/17491125/26620444/736ea9a8-4615-11e7-9704-9ddfc4b7b6bb.png">

**Comment by mauricecruz** [comment]
I patched it for the light theme. Should be out shortly.
