### ISSUE TITLE
Resize search bar in DOM inspector

### ISSUE THREAD

**Issue by Alex-302** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#185]
Hi
Is it possible to make it wide like in Chrome beta 59? I want it in older version(Chrome 46 - Slimjet browser)

<details>

![image](http://imagizer.imageshack.com/img922/4258/grRZSJ.png)
</details>
Chrome 59 beta
<details>

![image](http://imagizer.imageshack.com/img922/3092/oa22ha.png)
</details>

**Comment by mauricecruz** [comment]
Thanks for the report. Good find. That should be doable.



- Maurice

**Comment by mauricecruz** [comment]
Hmm - not sure if I can make it wide for older versions since the markup might be different. But I'll see what I can do.

**Comment by Alex-302** [comment]
Tried to change color of `.toolbar-search-control`, but Crome says that extansion is broken:(

**Comment by Alex-302** [comment]
@mauricecruz Any news?)

**Comment by Alex-302** [comment]
@mauricecruz hi!
I am sure you can do it:) I found that elements:

![image](http://imagizer.imageshack.com/img923/8972/SnZENC.png)

It should not interfere with new version of Chrome.

**Comment by Alex-302** [comment]
chrome-devtools://devtools/bundled/inspector.html
`body /deep/ span[class="toolbar-search-control"]` `width: 100%;`
`body /deep/ table[class="toolbar-search"]` `width: 100%;`

**Comment by mauricecruz** [comment]
should be available in the webstore soon.

**Comment by Alex-302** [comment]
@mauricecruz Excellent! Works in Chrome 58 and in my good old Chrome 46:)
