### ISSUE TITLE
[Suggestion] Change unreadable colors for Adguard pane

### ISSUE THREAD

**Issue by Alex-302** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#187]
Current colors:

<details>

![image](https://cloud.githubusercontent.com/assets/8361299/26763701/b203dbc8-495f-11e7-8ec3-c10862f70afc.png)
</details>
Suggested colors:
<details>

![image](https://cloud.githubusercontent.com/assets/8361299/26763707/c64724fa-495f-11e7-8ce9-2cd27c5c9013.png)
</details>
Suggested style:
<details>

`body.platform-mac` is unique. It prevents posible(or impossible:) ) interfere with other elements.

```
/* attribute value */
body.platform-mac .styles-section .style-properties li {
    color: #ff8737 !important;
}

/* attribute */
body.platform-mac span.webkit-css-property {
    color: #77a8c6 !important;
}

/* separators */
body.platform-mac div.sidebar-separator {
    background-color: #222 !important;
    border-top: 1px solid #343434 !important;
    border-bottom: 1px solid #101010 !important;
    color: #929292 !important;
}

/* buttons */
body.platform-mac input[class="action-button"] {
    color: #929292 !important;
    background-color: #222222 !important;
    border-color: #9E9E9E !important;
}

/* text input of the rule */
body.platform-mac input.rule-input {
    color: rgb(0, 255, 7) !important;
    background-color: #222222 !important;
    border-color: #9E9E9E !important;
}
```

</details>

The page of Adguard extension
https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg?utm_source=chrome-app-launcher-info-dialog

**Comment by mauricecruz** [comment]
Thanks for the report - will see what I can do.

**Comment by mauricecruz** [comment]
I'm not using any selectors that are OS specific. I think the adguard team has to fix this in their extension.

**Comment by Alex-302** [comment]
`.platform-mac` is used on any platform, even in Firefox on Android:)

> I think the adguard team has to fix this in their extension.

I am agree. Also I made a fixed version)
