### ISSUE TITLE
Ubuntu vs Mac difference?

### ISSUE THREAD

**Issue by peterhinners** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#188]
Love this theme, thank you! I noticed that in my virtual machine at work (ubuntu), zero dark matrix looks slightly different than on my mac at home -- not as good. Some of the tabs on top are white, for example, and when I write in the console the words are always white, along with the words in the suggestion box.

Is that normal behavior? Not the end of the world if that's the case, but I just love how this looks on mac and would hope to be able to have it look the same on the vm at work.

Thank you!
Pete

**Comment by mauricecruz** [comment]
Hey Pete, You're welcome! Glad you enjoy the theme.

I'm guessing that your Ubuntu version may be using a different version of chrome then your Mac. Not sure if they release them in the same version cycle. In any case, I try to support the latest stable versions and to a lesser extent, canary builds.

What version of chrome are you running on Ubuntu?

**Comment by peterhinners** [comment]
Hi Maurice, I think you are exactly right. Wish I could update chrome at
work but we're in  a VM with all these dependencies. Thanks for your help!

**Comment by mauricecruz** [comment]
FWIW, there's a native dark theme setting that may 'patch' things up for older versions. It's in the Settings -> Preferences panel.
