### ISSUE TITLE
This extension (v2.4.1) is incompatible with latest Chrome 60.0.3112.90 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by erotavlas** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#190]
When this extension is enabled it breaks the developer console output window - issue is that you cannot switch between the different output levels (Verbose, Info, Warning, Errors) in the Console.  It always remains on verbose or info, even if you select to display only warnings or errors.  

I had to turn the extension off in order for the console to work normally again.

**Comment by mauricecruz** [comment]
@erotavlas thanks for the report. The filters are working but the UI is not showing the checkbox. I just pushed up a fix which should be available shortly.

**Comment by mauricecruz** [comment]
@erotavlas should be resolved now. Please confirm.
