### ISSUE TITLE
"This extension may have been corrupted."

### ISSUE THREAD

**Issue by vaindil** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#191]
I'm not sure if this is the extension or something on my end, but almost every time I've opened Dev Tools today the extension has stopped working. If I go into the Chrome extensions menu, I'm met with the screenshot below. I can repair it (re-installs the extension), then it usually works properly the next time I open Dev Tools, but after that the same thing repeats. No other extensions are having this problem.

Chrome v60.0.3112.90 (latest as of posting)
Extension v2.4.2

![screenshot](https://user-images.githubusercontent.com/771134/29141628-fa901492-7d1c-11e7-8a6a-f9c20c890224.png)

**Comment by mauricecruz** [comment]
Hmm, I just released an update today. May be a bad build. I'll repackage
it. Thanks.

**Comment by Sluder** [comment]
Same issue. I installed through the Chrome store. Was this fixed?

**Comment by mauricecruz** [comment]
Uploaded a new package but I was getting the same error. I updated the tool I use to package the extension. Not sure if that's going to fix it. 

Not too sure what's going on yet. I haven't changed anything but css. Will dig into it some more.

**Comment by szuranski** [comment]
Same issue
Chrome Version 60.0.3112.90 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/4400466/29155068-f0cb9f2a-7d5e-11e7-8f84-9a7d13016567.png)

**Comment by mauricecruz** [comment]
Think it might have to do with an incremental update in v60. I had a
machine running v59 and it was fine. Gonna look for/file a bug report.

**Comment by mauricecruz** [comment]
Opened this ticket - https://bugs.chromium.org/p/chromium/issues/detail?id=754282. Star it to stay informed.

Not getting the error on Canary so maybe it'll resolve itself in a future release if they don't find any glaring issues..

**Comment by mauricecruz** [comment]
turns out it was a bug in the content verification check. It's been resolved in v61 but I fixed the extension for now.

> Summary: files that are of size equals multiple of content hash's block_size (4096 bytes) always fail content verification due to bug.

**Comment by hoangnamitc** [comment]
THANKS @mauricecruz !  your extendsion use normal.

**Comment by ttbarnes** [comment]
Thank you @mauricecruz, all is working with chrome version 60.0.3112.90 ❤️
