### ISSUE TITLE
Error CSS in Chrome version 61

### ISSUE THREAD

**Issue by hoangnamitc** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#192]
Hi @mauricecruz ,

I update chrome version 61 then error as image:

![image](https://user-images.githubusercontent.com/7042462/30143926-681a8488-93b2-11e7-830a-9c58197cb504.png)

Thanks !

**Comment by mauricecruz** [comment]
Thanks for the report. I'll take a look. In the meantime, can you enable the native dark theme and let me know if that fixes it?

**Comment by hoangnamitc** [comment]
Dark theme default is working oke !

![image](https://user-images.githubusercontent.com/7042462/30156263-63c85f0e-93e9-11e7-96f5-925200385811.png)

**Comment by mauricecruz** [comment]
just pushed out a fix. Should be up in the store in a short while.

**Comment by mauricecruz** [comment]
Can you verify if this is fixed?

**Comment by hoangnamitc** [comment]
Hi, Yes @mauricecruz  problem is fixed :) very thanks !

![image](https://user-images.githubusercontent.com/7042462/30220718-aa4803ec-94ea-11e7-9fe1-4a471784039a.png)
