### ISSUE TITLE
CSS Selectors changed from orange to grey all of a sudden

### ISSUE THREAD

**Issue by stereokai** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#193]
![image](https://user-images.githubusercontent.com/2685357/30266781-19408a62-96e9-11e7-825d-379d1fa1aa14.png)

I do like how only the relevant rule to the inspected element is being highlighted (in light grey), but the orange was bolder and helped focusing.

**Comment by mauricecruz** [comment]
Thanks for reporting! The latest version probably changed the selector
name. I'll have it fixed. Thanks!

**Comment by stereokai** [comment]
You are awesome! If you can keep the non-matching selectors in dark grey, and only highlight in orange the matching selector that would be spectacular and so helpful! Thanks you considering :)

**Comment by mauricecruz** [comment]
@stereokai fix should be in the latest version. Can you confirm?

**Comment by stereokai** [comment]
It's excellent, thank you!
