### ISSUE TITLE
Styles messed up all of a sudden

### ISSUE THREAD

**Issue by nodeworks** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#194]
Been using your extension for years. Love it! But just today I started noticing it's like this:

![Weird styles](https://i.snag.gy/lRaNX3.jpg)

Any ideas?

**Comment by mauricecruz** [comment]
Thanks! What version are you on?

**Comment by nodeworks** [comment]
2.5.1

**Comment by mauricecruz** [comment]
Sorry, I meant chrome version?

**Comment by nodeworks** [comment]
No worries:

Version 60.0.3112.113 (Official Build) (64-bit)

**Comment by mauricecruz** [comment]
Gotcha - think stable is on `61` now. Try updating.

**Comment by nodeworks** [comment]
That fixed it!! You're the best! thanks again!
