### ISSUE TITLE
Unreadable colours

### ISSUE THREAD

**Issue by ttbarnes** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#195]
Hello, I know this is temporarily only supporting the stable channel right now and this needs a rewrite, so i'm sure @mauricecruz is more than aware of this issue:

![screen shot 2017-09-12 at 10 48 48](https://user-images.githubusercontent.com/2463648/30319702-73ffdc90-97a8-11e7-906c-3560a78f791e.png)

I would like to contribute to the rewrite, if I can. ? This theme is fantastic, it's invaluable for me day-to-day 😄

**Comment by stephen-crowdreactive** [comment]
I'm getting this too

**Comment by mauricecruz** [comment]
Chrome Stable is on m61 now. Please try updating your browser.

**Comment by ttbarnes** [comment]
Working beautifully after updating chrome; I wonder why it didn't auto-update 🙃 

Let me know if you want help with the rewrite @mauricecruz
