### ISSUE TITLE
Weird colours suddently

### ISSUE THREAD

**Issue by Zuwie** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#196]
Hello!
Great work but lately it is using very dark colors, not those I am used to.
Any suggestions how I can fix this?
<img width="1440" alt="screen shot 2017-09-13 at 19 51 56" src="https://user-images.githubusercontent.com/25747851/30392501-5399db02-98bd-11e7-84e9-519cc76f9fca.png">

**Comment by mauricecruz** [comment]
Think you're on an old chrome version. Please update.

**Comment by Zuwie** [comment]
This was indeed the issue; thanks for the quick support.

**Comment by Frozenlock** [comment]
Same problem here.
Everything was fine until 1-3 days ago.
Version 60.0.3112.113 (Developer Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by mauricecruz** [comment]
Is m61 available for Ubuntu?

**Comment by mauricecruz** [comment]
@Frozenlock, Is m61 available for Ubuntu?

**Comment by Frozenlock** [comment]
Updating now. 

FWIW I also have `Chrome Version 60.0.3112.90 (Official Build) (64-bit)` and it didn't warn me of a new version (yet). Same issue.

**Comment by Frozenlock** [comment]
Everything looks nice on version 61. :+1:
