### ISSUE TITLE
theme not applied to sources in 60.0.3112.113

### ISSUE THREAD

**Issue by tommyyork** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#197]
It doesn't like the theme is being applied to the sources tab in 60.0.3112.113.

**Comment by mauricecruz** [comment]
Hey so sorry I just saw this now. Are you still having issues? Stable is on m62 now. A few styles need to be updated.

**Comment by tommyyork** [comment]
No issues anymore since I updated chrome!
