### ISSUE TITLE
problem with style since the october 2017 update

### ISSUE THREAD

**Issue by abourtnik** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#198]
Hello since the update I have problem with style in my inspector.

![capture du 2017-10-19 14-09-12](https://user-images.githubusercontent.com/23094492/31770245-2c24a7ce-b4d7-11e7-9d03-b5b195b54629.png)

Thank you for your answer and have a good day ;)

**Comment by mauricecruz** [comment]
Please update your browser version.

**Comment by brianbautista** [comment]
Updating to Chrome 62.0.3202.62 has resolved this issue for me as well

**Comment by fjandakornid** [comment]
Had the same issue in version 61.0.3163.100. 
Fixed it by changing DevTools settings -> Preferences -> Theme: Dark
