### ISSUE TITLE
Selector color of very dark selectors

### ISSUE THREAD

**Issue by marciosena** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#202]
## Problem

When you select the value of an HTML attribute (Ex: class) the theme colors make it very difficult to see the content. A light color (#fff) would be the solution.

![captura de tela 2018-06-11 as 10 08 11](https://user-images.githubusercontent.com/3450717/41234864-cbb94d0e-6d63-11e8-9aac-a59731e921b4.png)

## Configuration
- MacOS (10.13.4)
- Chrome (66.0.3359.181 64 bits)
- DevTools Theme: Zero Dark Matrix (3.0.4)

## Solved

Dev Tool > Settings > Preferences > Appearance > Theme: Dark

![captura de tela 2018-06-11 as 10 38 06](https://user-images.githubusercontent.com/3450717/41234790-8e64166e-6d63-11e8-97d9-592df006ce08.png)

**Comment by mauricecruz** [comment]
Thanks for the report. Just updated the instructions to notify users to enable the dark theme.
