### ISSUE TITLE
color in styles tab of elements when typing unreadable

### ISSUE THREAD

**Issue by jgerstle** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#207]
When adding manual styling in the styles tab on the right side of the elements tab, the text you are typing is not legible, my guess is that the color and background color are the same.
![image](https://user-images.githubusercontent.com/13005080/57290127-74165680-70c5-11e9-896f-14a505d7d53e.png)

I have been having this issue for the last couple (possibly more) months. I figured maybe it'd get fixed, but it hasn't yet

**Comment by mauricecruz** [comment]
Can you enable the native dark theme. It'll act as a fallback to styles
that don't render well/can't be styled.

I'll take a look. Thanks!

**Comment by jgerstle** [comment]
Alright enabling the dark theme works as a workaround, thanks.
