### ISSUE TITLE
Latest version of Chrome breaks custom themes

### ISSUE THREAD

**Issue by taniarascia** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#208]
I made a custom theme based on this one, and it seems like in version `76.0.3809.100`, these themes stopped working. Is anyone else experiencing this?

**Comment by mauricecruz** [comment]
Can you check if custom UI themes is checked off in the `Experiements` Tab. I had to turn it back on after updating. 

![image](https://user-images.githubusercontent.com/1640686/62951814-a3212000-bdb8-11e9-915a-58765087c8dc.png)

**Comment by taniarascia** [comment]
Well, don't I feel silly for not checking! Weird that this update would mess with the settings. Thanks!
