### ISSUE TITLE
React DevTools Theme

### ISSUE THREAD

**Issue by markbrouch** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#91]
I would love it if there was support for the React DevTools panel that gets added by the [React plugin](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi).

This is what it looks like currently:
![image](https://cloud.githubusercontent.com/assets/5997332/3417729/84ba457e-fe3c-11e3-91f3-ff41256fb8b1.png)

**Comment by mauricecruz** [comment]
FYI... made this an injectable so you don't have to dig into the filesystem.

https://gist.github.com/mauricecruz/f53c932961a04c01a096#file-zdm-react-devtools-md

**Comment by dqisme** [comment]
I found the way above doesn't work any more, so I hacked the react devtools packed chrome extension and re-design it into Tomorrow theme. 

[https://github.com/dqisme/react-devtool-with-tomorrow-theme](https://github.com/dqisme/react-devtool-with-tomorrow-theme)

**Comment by mauricecruz** [comment]
@dqisme awesome! Wonder if react devtools works with the native dark theme as well.

**Comment by dqisme** [comment]
@mauricecruz I looked into the extension package and the color is hard-coded in it. Facebook made devtools as inline styling for some React Native reason. so i think it doesn't work either.
